javascript:(()=>{
  if(window.__NETPRO__){window.__NETPRO__.toggle();return;}
  const D=document,W=window;
  const ST={logs:[],sel:null,rec:true,filter:'all',q:'',seq:0};
  const CSS='all:initial;box-sizing:border-box;font-family:Arial,sans-serif;color:#e9eef5;';
  function E(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function C(t,n=60000){t=String(t??'');return t.length>n?t.slice(0,n)+'\n...[TRUNCATED '+(t.length-n)+' chars]':t;}
  function P(t){try{return JSON.stringify(JSON.parse(t),null,2)}catch(e){return t??''}}
  function M(s){return String(s??'').replace(/(authorization\s*[:=]\s*["']?)(bearer\s+)?[^\s"'&,}]+/ig,'$1$2***MASKED***').replace(/(cookie\s*[:=]\s*["']?)[^\n]+/ig,'$1***MASKED***').replace(/((access_|refresh_)?token\s*[:=]\s*["']?)[^\s"'&,}]+/ig,'$1***MASKED***').replace(/(password\s*[:=]\s*["']?)[^\s"'&,}]+/ig,'$1***MASKED***');}
  function BT(b){try{if(!b)return'';if(typeof b==='string')return b;if(b instanceof URLSearchParams)return b.toString();if(b instanceof FormData){let a=[];b.forEach((v,k)=>a.push(k+'='+(v instanceof File?'[File:'+v.name+']':v)));return a.join('&')}if(b instanceof Blob)return'[Blob '+b.type+' '+b.size+' bytes]';if(b instanceof ArrayBuffer)return'[ArrayBuffer '+b.byteLength+' bytes]';return JSON.stringify(b)}catch(e){return'[unreadable body]'}}
  function HO(h){let o={};try{if(!h)return o;if(h.forEach)h.forEach((v,k)=>o[k]=v);else if(Array.isArray(h))h.forEach(x=>o[x[0]]=x[1]);else Object.keys(h).forEach(k=>o[k]=h[k]);}catch(e){}return o;}
  function HSTR(o){return Object.keys(o||{}).map(k=>k+': '+o[k]).join('\n');}
  function parseXHRHeaders(s){let o={};String(s||'').trim().split(/[\r\n]+/).forEach(l=>{let i=l.indexOf(':');if(i>0)o[l.slice(0,i).trim()]=l.slice(i+1).trim()});return o;}
  function copy(t){try{navigator.clipboard.writeText(t);toast('Copied')}catch(e){console.log(t);toast('Copy gagal, lihat console')}}
  function toast(t){let x=D.getElementById('__np_toast');if(!x){x=D.createElement('div');x.id='__np_toast';x.style.cssText=CSS+'position:fixed;left:50%;bottom:78px;transform:translateX(-50%);z-index:2147483647;background:#111;border:1px solid #555;border-radius:999px;padding:8px 14px;font-size:12px;';D.body.appendChild(x)}x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',1200)}
  function mk(tag,css,html){let el=D.createElement(tag);el.style.cssText=CSS+css;if(html!=null)el.innerHTML=html;return el;}
  const btn=mk('button','position:fixed;right:10px;bottom:12px;z-index:2147483647;width:50px;height:50px;border-radius:999px;border:1px solid #6b7280;background:#111827;color:#fff;font:700 13px Arial;box-shadow:0 8px 24px #0008;','NET');
  const panel=mk('div','display:none;position:fixed;left:4px;right:4px;bottom:68px;height:72vh;z-index:2147483646;background:#0b1220;border:1px solid #334155;border-radius:12px;box-shadow:0 10px 35px #000a;overflow:hidden;');
  panel.innerHTML=`<div style="display:flex;gap:6px;align-items:center;padding:7px;border-bottom:1px solid #263244;background:#111827"><b style="flex:1;color:#fff;font:700 13px Arial">Network Pro</b><button id="np_rec">REC</button><button id="np_all">All</button><button id="np_fx">Fetch</button><button id="np_xhr">XHR</button><button id="np_err">Err</button><button id="np_clear">Clear</button><button id="np_close">×</button></div><div style="display:flex;gap:6px;padding:6px;border-bottom:1px solid #263244"><input id="np_q" placeholder="filter url/status/method" style="flex:1;background:#020617;color:#e5e7eb;border:1px solid #334155;border-radius:8px;padding:8px;font:12px Arial"></div><div id="np_body" style="display:grid;grid-template-columns:44% 56%;height:calc(72vh - 92px)"><div id="np_list" style="overflow:auto;border-right:1px solid #263244"></div><div id="np_detail" style="overflow:auto"></div></div>`;
  D.documentElement.appendChild(btn);D.documentElement.appendChild(panel);
  function activeBtns(){['all','fx','xhr','err'].forEach(x=>{let b=D.getElementById('np_'+x);if(b)b.style.background=(ST.filter===x?'#2563eb':'#1f2937')});let r=D.getElementById('np_rec');if(r)r.style.background=ST.rec?'#dc2626':'#374151'}
  function item(l){let ok=String(l.status).startsWith('2')||String(l.status).startsWith('3');return `<div data-id="${l.id}" style="padding:8px;border-bottom:1px solid #1f2a3a;${ST.sel===l.id?'background:#1d4ed8':'background:#0b1220'}"><div style="display:flex;gap:5px"><b style="color:${ok?'#86efac':'#fca5a5'}">${E(l.status)}</b><span>${E(l.method)}</span><span style="margin-left:auto;color:#94a3b8">${E(l.ms)}ms</span></div><div style="word-break:break-all;color:#93c5fd;font-size:11px">${E(l.url)}</div><div style="color:#94a3b8;font-size:11px">${E(l.type)} • ${E(l.time)} • ${E(l.size)}b</div></div>`}
  function match(l){let q=ST.q.toLowerCase();let f=ST.filter;if(f==='fx'&&l.type!=='fetch')return false;if(f==='xhr'&&l.type!=='xhr')return false;if(f==='err'&&!(String(l.status).startsWith('4')||String(l.status).startsWith('5')||String(l.status)==='ERR'))return false;if(!q)return true;return (l.url+' '+l.method+' '+l.status+' '+l.type).toLowerCase().includes(q)}
  function render(){activeBtns();let list=D.getElementById('np_list'),det=D.getElementById('np_detail');if(!list||!det)return;let arr=ST.logs.filter(match).slice().reverse();list.innerHTML=arr.map(item).join('')||'<div style="padding:10px;color:#94a3b8">Belum ada request. Klik fitur web setelah REC aktif.</div>';list.querySelectorAll('[data-id]').forEach(n=>n.onclick=()=>{ST.sel=+n.dataset.id;render()});let l=ST.logs.find(x=>x.id===ST.sel)||arr[0];if(l){ST.sel=l.id;det.innerHTML=detail(l)}else det.innerHTML='<div style="padding:12px;color:#94a3b8">Pilih request untuk lihat Headers / Payload / Response.</div>'}
  function detail(l){let raw=JSON.stringify(l,null,2);let curl=`curl -X ${l.method} '${l.url}'`+Object.keys(l.reqHeaders||{}).map(k=>` \\\n  -H '${k}: ${String(l.reqHeaders[k]).replace(/'/g,"'\\''")}'`).join('')+(l.payload?` \\\n  --data '${String(l.payload).replace(/'/g,"'\\''")}'`:'');return `<div style="padding:9px"><div style="display:flex;gap:6px;flex-wrap:wrap"><button id="np_cp_raw">Copy Raw</button><button id="np_cp_res">Copy Response</button><button id="np_cp_pay">Copy Payload</button><button id="np_cp_curl">Copy cURL</button></div><h3 style="font:700 14px Arial;color:#fff;margin:10px 0 6px">General</h3><pre>${E(M(`URL: ${l.url}\nMethod: ${l.method}\nStatus: ${l.status}\nType: ${l.type}\nDuration: ${l.ms}ms\nTime: ${l.time}\nSize: ${l.size} bytes`))}</pre><details open><summary>Request Headers</summary><pre>${E(M(HSTR(l.reqHeaders)||'(empty/cannot read)'))}</pre></details><details open><summary>Response Headers</summary><pre>${E(M(HSTR(l.resHeaders)||'(empty/cannot read)'))}</pre></details><details open><summary>Payload / Request Body</summary><pre>${E(M(l.payload||'(empty)'))}</pre></details><details open><summary>Response</summary><pre>${E(M(P(l.response||'')))}</pre></details><details><summary>Raw JSON</summary><pre>${E(M(raw))}</pre></details></div>`}
  panel.addEventListener('click',e=>{let l=ST.logs.find(x=>x.id===ST.sel);if(!l)return;if(e.target.id==='np_cp_raw')copy(M(JSON.stringify(l,null,2)));if(e.target.id==='np_cp_res')copy(M(l.response||''));if(e.target.id==='np_cp_pay')copy(M(l.payload||''));if(e.target.id==='np_cp_curl'){let curl=`curl -X ${l.method} '${l.url}'`+Object.keys(l.reqHeaders||{}).map(k=>` \\\n  -H '${k}: ${String(l.reqHeaders[k]).replace(/'/g,"'\\''")}'`).join('')+(l.payload?` \\\n  --data '${String(l.payload).replace(/'/g,"'\\''")}'`:'');copy(M(curl))}});
  D.getElementById('np_rec').onclick=()=>{ST.rec=!ST.rec;render()};D.getElementById('np_clear').onclick=()=>{ST.logs=[];ST.sel=null;render()};D.getElementById('np_close').onclick=()=>panel.style.display='none';D.getElementById('np_q').oninput=e=>{ST.q=e.target.value;render()};D.getElementById('np_all').onclick=()=>{ST.filter='all';render()};D.getElementById('np_fx').onclick=()=>{ST.filter='fx';render()};D.getElementById('np_xhr').onclick=()=>{ST.filter='xhr';render()};D.getElementById('np_err').onclick=()=>{ST.filter='err';render()};btn.onclick=()=>{panel.style.display=panel.style.display==='none'?'block':'none';render()};
  function add(l){if(!ST.rec)return;l.id=++ST.seq;l.time=new Date().toLocaleTimeString();l.size=String(l.response||'').length;ST.logs.push(l);W.__API_LOGS__=ST.logs;ST.sel=l.id;console.groupCollapsed('🌐 '+l.type+' '+l.method+' '+l.status+' '+l.url);console.log(l);console.groupEnd();render();}
  const OF=W.fetch;if(OF&&!OF.__np){W.fetch=async function(input,init={}){let st=performance.now(),url='',method='GET',payload='',reqHeaders={};try{if(input instanceof Request){url=input.url;method=input.method;reqHeaders=HO(input.headers)}else url=String(input);if(init&&init.method)method=init.method;if(init&&init.headers)reqHeaders={...reqHeaders,...HO(init.headers)};if(init&&init.body)payload=BT(init.body)}catch(e){}try{let r=await OF.apply(this,arguments),txt='';try{txt=C(await r.clone().text())}catch(e){txt='[unreadable response: '+e.message+']'}add({type:'fetch',url,method,status:r.status,ms:Math.round(performance.now()-st),reqHeaders,resHeaders:HO(r.headers),payload,response:txt});return r}catch(e){add({type:'fetch',url,method,status:'ERR',ms:Math.round(performance.now()-st),reqHeaders,resHeaders:{},payload,response:String(e)});throw e}};W.fetch.__np=1}
  const XO=XMLHttpRequest.prototype.open,XS=XMLHttpRequest.prototype.send,XH=XMLHttpRequest.prototype.setRequestHeader;if(!XMLHttpRequest.prototype.__np){XMLHttpRequest.prototype.open=function(m,u){this.__np_m=m;this.__np_u=u;this.__np_h={};return XO.apply(this,arguments)};XMLHttpRequest.prototype.setRequestHeader=function(k,v){this.__np_h=this.__np_h||{};this.__np_h[k]=v;return XH.apply(this,arguments)};XMLHttpRequest.prototype.send=function(b){let x=this,st=performance.now(),payload=BT(b);x.addEventListener('loadend',()=>{let tx='';try{tx=C(x.responseText)}catch(e){tx='[unreadable xhr response]'}add({type:'xhr',url:x.__np_u,method:x.__np_m,status:x.status,ms:Math.round(performance.now()-st),reqHeaders:x.__np_h||{},resHeaders:parseXHRHeaders(x.getAllResponseHeaders()),payload,response:tx})});return XS.apply(this,arguments)};XMLHttpRequest.prototype.__np=1}
  W.__NETPRO__={toggle:()=>btn.click(),open:()=>{panel.style.display='block';render()},state:ST};
  panel.style.display='block';render();toast('Network Pro aktif');
})();
